# Generated by Django 5.2.8 on 2025-11-22 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('meta_monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ahorro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_estimado', models.CharField(help_text='Ej: 365 días, 12 meses', max_length=50)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#FFB4A8', 'Coral'), ('#FFCBA8', 'Durazno'), ('#E8F48C', 'Amarillo Claro'), ('#B8E6B8', 'Verde Claro'), ('#B4D4FF', 'Azul Claro'), ('#FFD6EC', 'Rosa Claro')], default='#FFB4A8', max_length=7)),
                ('imagen', models.CharField(default='general', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'metas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='metas.meta')),
            ],
            options={
                'verbose_name': 'Aporte a Meta',
                'verbose_name_plural': 'Aportes a Metas',
                'db_table': 'aportes_meta',
                'ordering': ['-fecha'],
            },
        ),
    ]
